[workspace]
members = ["crates/*", "examples/*", "tests-integration"]
resolver = "2"

[workspace.package]
version = "0.0.1"
edition = "2024"
authors = ["Riccardo Mazzarini <me@noib3.dev>", "c-c-k <c-c-k@nym.hush.com>"]
rust-version = "1.95.0"
documentation = "https://docs.rs/nvim-oximlua"
repository = "https://github.com/c-c-k/nvim-oximlua"
license = "MIT"
keywords = ["bindings", "neovim", "nvim", "mlua"]

[workspace.dependencies]
# 3rd-party dependencies.
cargo_metadata = "0.23"
libc = "0.2"
proc-macro2 = "1"
quote = "1"
serde = "1"
serde_repr = "0.1"
syn = "2"
thiserror = "2"
tokio = "1"

# NOTE: The version and features of `mlua` must be in sync
#       between `nvim-oximlua` and `mlua-extras`!
mlua = { version = "0.11.6", features = ["luajit", "serde"] }
mlua-extras = { version = "11.6.2", features = ["luajit"] }

# Internal dependencies.
api = { path = "./crates/api", package = "nvim-oximlua-api" }
libuv = { path = "./crates/libuv", package = "nvim-oximlua-libuv" }
macros = { path = "./crates/macros", package = "nvim-oximlua-macros" }
olua = { path = "./crates/olua", package = "nvim-oximlua-olua" }
types = { path = "./crates/types", package = "nvim-oximlua-types" }
vimfn = { path = "./crates/vimfn", package = "nvim-oximlua-vimfn" }

[workspace.lints.clippy]
mixed_attributes_style = "allow"

[workspace.lints.rust]
unsafe_op_in_unsafe_fn = "allow"

[workspace.lints.rustdoc]
broken_intra_doc_links = "deny"
private_intra_doc_links = "deny"

[package]
name = "nvim-oximlua"
description = "Rust bindings to all things Neovim"
readme = "./README.md"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
default-features = false
features = ["__docsrs", "neovim-nightly", "libuv", "mlua", "test"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["__no_docsrs"]
neovim-0-11 = ["api/neovim-0-11"]
neovim-0-12 = ["neovim-0-11", "api/neovim-0-12"]
neovim-nightly = ["neovim-0-12", "api/neovim-nightly"]

__docsrs = ["mlua/vendored"]
__no_docsrs = ["mlua/module"]

libuv = ["dep:libuv"]
test = ["macros/test", "dep:cargo_metadata"]
test-terminator = ["test", "libuv", "macros/test-terminator"]

# mlua and mlua-extras re-exports
mlua-extras = ["dep:mlua-extras"]
async = ["mlua/async", "mlua-extras?/async"]
error-send = ["mlua/error-send", "mlua-extras?/error-send"]
macros = ["mlua/macros", "mlua-extras?/macros"]
anyhow = ["mlua/anyhow", "mlua-extras?/anyhow"]
userdata-wrappers = ["mlua/userdata-wrappers", "mlua-extras?/userdata-wrappers"]

[dependencies]
api = { workspace = true }
libuv = { workspace = true, optional = true }
macros = { workspace = true, features = ["plugin"] }
olua = { workspace = true }
types = { workspace = true, features = ["serde"] }
vimfn = { workspace = true }

cargo_metadata = { workspace = true, optional = true }
mlua = { workspace = true }
mlua-extras = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
serde = { workspace = true, features = ["derive"] }
tokio = { workspace = true, features = ["full"] }

[[example]]
name = "nvim_api"
path = "./examples/nvim_api.rs"
crate-type = ["cdylib"]

[[example]]
name = "exports"
path = "./examples/exports.rs"
crate-type = ["cdylib"]

[[example]]
name = "exports_compatibility"
path = "./examples/exports_compatibility.rs"
crate-type = ["cdylib"]

[[example]]
name = "libuv"
path = "./examples/libuv.rs"
crate-type = ["cdylib"]
required-features = ["libuv"]

[[example]]
name = "serde"
path = "./examples/serde.rs"
crate-type = ["cdylib"]
