[package]
name = "nvim-oximlua-vimfn"
description = "Rust bindings to Neovim's Vimscript functions for nvim-oximlua"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[package.metadata.docs.rs]
default-features = false
features = ["__docsrs", "neovim-nightly", "mlua"]
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = ["__no_docsrs"]
neovim-0-11 = []
neovim-0-12 = ["neovim-0-11"]
neovim-nightly = ["neovim-0-12"]

__docsrs = ["mlua/vendored"]
__no_docsrs = ["mlua/module"]

[dependencies]
api = { workspace = true }
macros = { workspace = true }
mlua = { workspace = true, features = ["serde"] }
olua = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_repr = { workspace = true }
thiserror = { workspace = true }
types = { workspace = true, features = ["serde"] }


[lints]
workspace = true
