[package]
name = "nvim-oximlua-olua"
description = "core utils and mlua adapter for nvim-oximlua"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true
documentation.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true

[dependencies]
mlua = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
