[package]
name = "nvim-oximlua-tests-integration"
version.workspace = true
edition.workspace = true
publish = false

[lib]
crate-type = ["cdylib"]

[features]
default = ["neovim-0-11"]
neovim-0-11 = ["nvim-oximlua/neovim-0-11"]
neovim-0-12 = ["neovim-0-11", "nvim-oximlua/neovim-0-12"]
neovim-nightly = ["neovim-0-12", "nvim-oximlua/neovim-nightly"]

[dependencies]
all_asserts = "2.3"
thiserror = { workspace = true }
mlua = { workspace = true, features = ["error-send"] }

[target.'cfg(not(any(target_os = "windows", target_env = "msvc")))'.dependencies]
nvim-oximlua = { path = "..", features = ["libuv", "test"] }

# Enabling libuv will cause the build to fail on Windows.
[target.'cfg(any(target_os = "windows", target_env = "msvc"))'.dependencies]
nvim-oximlua = { path = "..", features = ["test"] }

[build-dependencies]
nvim-oximlua = { path = "..", features = ["test"] }
